version: '3.8'

services:
  kernel-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blissos-kernel-builder
    volumes:
      # Mount kernel source (will be cloned if not exists)
      - ./kernel-source-xanmod:/kernel-source
      # Mount build output directory
      - ./kernel-build-xanmod:/kernel-build
      # Mount BlissOS kernel config
      - ./kernel.config:/config/kernel.config:ro
      # Mount our Broadcom driver with fixes
      - ./drivers:/drivers:ro
      # Cache for faster rebuilds
      - kernel-cache:/root/.cache
    environment:
      # Kernel version
      - KERNEL_VERSION=6.9.9
      - KERNEL_LOCALVERSION=-zenith
      # Build settings
      - KBUILD_BUILD_USER=jack
      - KBUILD_BUILD_HOST=orion
      # Parallel jobs
      - JOBS=8
    command: |
      bash -c "
        # Clone kernel source if not exists
        if [ ! -f /kernel-source/Makefile ]; then
          echo '=== Downloading Linux kernel 6.9.9 ==='
          cd /tmp
          git clone --depth 1 --branch 6.9_xanmod https://github.com/android-generic/kernel-zenith.git kernel-tmp
          
          # Copy to mounted volume
          cp -r kernel-tmp/* /kernel-source/ 2>/dev/null || {
            echo 'Cannot write to /kernel-source. Creating it on host...'
            exit 1
          }
          echo '=== Kernel source downloaded ==='
        else
          echo '=== Using existing kernel source ==='
        fi
        
        # Copy our broadcom-wl driver to kernel source
        echo '=== Installing Broadcom BCM4352 driver ==='
        mkdir -p /kernel-source/drivers/net/wireless/
        if [ -d /drivers/broadcom-wl ]; then
          echo 'Copying driver from /drivers/broadcom-wl to kernel source...'
          cp -rv /drivers/broadcom-wl /kernel-source/drivers/net/wireless/ 2>&1 | head -20
          
          # CRITICAL: Verify the copy actually worked
          if [ ! -d /kernel-source/drivers/net/wireless/broadcom-wl ]; then
            echo 'ERROR: Failed to copy driver to kernel source!'
            exit 1
          fi
          
          # Check that essential files exist
          if [ ! -f /kernel-source/drivers/net/wireless/broadcom-wl/Makefile ]; then
            echo 'ERROR: Makefile not found after copy!'
            exit 1
          fi
          
          if [ ! -f /kernel-source/drivers/net/wireless/broadcom-wl/Kconfig ]; then
            echo 'ERROR: Kconfig not found after copy!'
            exit 1
          fi
          
          echo 'Driver copied successfully. Contents:'
          ls -la /kernel-source/drivers/net/wireless/broadcom-wl/ | head -10
        else
          echo 'ERROR: /drivers/broadcom-wl not found!'
          ls -la /drivers/
          exit 1
        fi
        
        # Add driver to Kconfig and Makefile if not already added
        echo '=== Integrating driver into kernel build system ==='
        
        # Add to Kconfig
        if ! grep -q 'source \"drivers/net/wireless/broadcom-wl/Kconfig\"' /kernel-source/drivers/net/wireless/Kconfig 2>/dev/null; then
          echo 'Adding broadcom-wl to Kconfig...'
          echo 'source \"drivers/net/wireless/broadcom-wl/Kconfig\"' >> /kernel-source/drivers/net/wireless/Kconfig
        else
          echo 'broadcom-wl already in Kconfig'
        fi
        
        # Add to Makefile (and remove old wrong entries)
        echo 'Cleaning up old wrong CONFIG_WL entries...'
        sed -i '/obj-\$$(CONFIG_WL).*broadcom-wl/d' /kernel-source/drivers/net/wireless/Makefile
        
        if ! grep -q 'obj-\$$(CONFIG_WLAN_VENDOR_BROADCOM_WL).*broadcom-wl' /kernel-source/drivers/net/wireless/Makefile 2>/dev/null; then
          echo 'Adding broadcom-wl to Makefile with correct CONFIG...'
          echo 'obj-\$$(CONFIG_WLAN_VENDOR_BROADCOM_WL) += broadcom-wl/' >> /kernel-source/drivers/net/wireless/Makefile
        else
          echo 'broadcom-wl already in Makefile with correct CONFIG'
        fi
        
        # Verify integration
        echo '=== Verifying integration ==='
        echo 'Checking Kconfig:'
        grep 'broadcom-wl' /kernel-source/drivers/net/wireless/Kconfig || echo 'ERROR: Not found in Kconfig!'
        echo 'Checking Makefile for CORRECT config:'
        if grep -q 'CONFIG_WLAN_VENDOR_BROADCOM_WL.*broadcom-wl' /kernel-source/drivers/net/wireless/Makefile; then
          echo '  ✓ CORRECT: CONFIG_WLAN_VENDOR_BROADCOM_WL'
          grep 'CONFIG_WLAN_VENDOR_BROADCOM_WL.*broadcom-wl' /kernel-source/drivers/net/wireless/Makefile
        else
          echo '  ✗ ERROR: CONFIG_WLAN_VENDOR_BROADCOM_WL not found!'
        fi
        if grep -q 'CONFIG_WL.*broadcom-wl' /kernel-source/drivers/net/wireless/Makefile; then
          echo '  ✗ ERROR: Found WRONG CONFIG_WL! This will NOT work!'
          grep 'CONFIG_WL.*broadcom-wl' /kernel-source/drivers/net/wireless/Makefile
        fi
        
        # Run build script
        /usr/local/bin/build-kernel.sh
      "
    networks:
      - build-network

  # Optional: source downloader service
  source-downloader:
    image: alpine/git:latest
    container_name: kernel-source-downloader
    volumes:
      - ./kernel-source-xanmod:/source
    command: |
      sh -c "
        if [ ! -f /source/Makefile ]; then
          echo 'Cloning kernel source v6.9.9...'
          git clone --depth 1 --branch 6.9_xanmod https://github.com/android-generic/kernel-zenith.git /tmp/linux
          cp -r /tmp/linux/* /source/
          echo 'Source download complete'
        else
          echo 'Source already exists'
        fi
      "
    networks:
      - build-network
    profiles:
      - download

volumes:
  kernel-cache:
    driver: local

networks:
  build-network:
    driver: bridge