version: '3.8'

services:
  kernel-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blissos-kernel-builder
    volumes:
      # Mount kernel source (will be cloned if not exists)
      - ./kernel-source-xanmod:/kernel-source
      # Mount build output directory
      - ./kernel-build-xanmod:/kernel-build
      # Mount BlissOS kernel config
      - ./kernel.config:/config/kernel.config:ro
      # Mount our Broadcom driver with fixes
      - ./drivers:/drivers:ro
      # Cache for faster rebuilds
      - kernel-cache:/root/.cache
    environment:
      # Kernel version
      - KERNEL_VERSION=6.9.9
      - KERNEL_LOCALVERSION=-zenith
      # Build settings
      - KBUILD_BUILD_USER=jack
      - KBUILD_BUILD_HOST=orion
      # Parallel jobs
      - JOBS=8
    command: /usr/local/bin/install-broadcom-driver.sh && /usr/local/bin/build-kernel.sh
    networks:
      - build-network

  # Optional: source downloader service
  source-downloader:
    image: alpine/git:latest
    container_name: kernel-source-downloader
    volumes:
      - ./kernel-source-xanmod:/source
    command: |
      sh -c "
        if [ ! -f /source/Makefile ]; then
          echo 'Cloning kernel source v6.9.9...'
          git clone --depth 1 --branch 6.9_xanmod https://github.com/android-generic/kernel-zenith.git /tmp/linux
          cp -r /tmp/linux/* /source/
          echo 'Source download complete'
        else
          echo 'Source already exists'
        fi
      "
    networks:
      - build-network
    profiles:
      - download

volumes:
  kernel-cache:
    driver: local

networks:
  build-network:
    driver: bridge